[package]
name = "pbf_font_tools"
version = "0.3.0"
authors = ["Ian Wagner <ian@stadiamaps.com>"]
license = "BSD-3-Clause"
repository = "https://github.com/stadiamaps/pbf_font_tools"
readme = "README.md"
description = "Tools for working with SDF font glyphs encoded in protobuf format."
keywords = ["sdf", "protobuf", "fonts"]
categories = ["encoding", "parsing", "rendering::data-formats"]
edition = "2018"

[dependencies]
futures = "~0.3"
protobuf = "~2.18"

[dependencies.tokio]
version = "~1.0"
features = ["fs", "io-util"]

[build-dependencies]
glob = "~0.3"
protobuf-codegen-pure = "~2.18"

[dev-dependencies.tokio]
version = "~1.0"
features = ["fs", "io-util", "macros", "rt"]
