[package]
name = "build_pbf_glyphs"
version = "1.0.1"
authors = ["Ian Wagner <ian@stadiamaps.com>"]
license = "BSD-3-Clause"
repository = "https://github.com/stadiamaps/build_pbf_glyphs"
readme = "README.md"
description = "Tools for working with SDF font glyphs encoded in protobuf format."
keywords = ["sdf", "protobuf", "fonts"]
categories = ["encoding", "parsing", "rendering::data-formats"]
edition = "2018"

[dependencies]
clap = "2.33.3"
freetype-rs = "0.27.0"
num_cpus = "1.13.0"
protobuf = "2.22.1"
spmc = "0.3.0"

[dependencies.pbf_font_tools]
version = "1.0.2"
features = ["freetype"]
