on:
  release:
    types: [ published ]

name: Cargo Publish

jobs:
  publish:
    if: false
    name: Publish with ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            target: linux.x86_64
          - os: macos-latest
            target: macos

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish
        uses: actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: publish
          args: --all-features

  build:
    name: Build Binaries with ${{ matrix.os }}
    if: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --release
      - name: Push Artifacts
        run: gh release upload $GITHUB_REF_NAME target/release/build_pbf_glyphs#build_pbf_glyphs.${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Publish on Release
#        if: github.event.release.published == true
#        env:
#          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
#        run: cargo publish -p pbf_font_tools --all-features
